<div id="content">
	<div class="content-wrapper">		
		<div class="row">
			<div class="col-lg-12 heading">
                <h1 class="page-header"><i class="ec-pencil2"></i>Lista de Paciente</h1>
                <ul id="crumb" class="breadcrumb">
                </ul>
                <div class="option-buttons">
                    <div class="btn-toolbar" role="toolbar">
                        <div class="btn-group">
                            <a class="btn dropdown-toggle" id="dropdownMenu1" href="<?php echo $this->baseUrl('/corporativo/cliente/')?>">
								<button class="btn btn-primary" type="button">Adicionar Paciente</button>
							</a>
                        </div>
                    </div>
                </div>
            </div>
		</div>
		
		<?php if(!empty($this->rsPacientes)):?>
		
			<div class="outlet">
    			<form class="form-horizontal group-border hover-stripped" role="form">
					<div class="row">
    					<div class="col-lg-12">
							<div class="panel panel-default plain toggle panelClose panelRefresh">
								<div class="panel-heading">
									<h4 class="panel-title">Relatório</h4>
								</div>
								<div class="panel-body">
									<table id="responsive-datatables" class="table table-bordered table-striped table-hover dt-responsive non-responsive" >
										<thead>
											<tr>
												<th>Registro</th>
												<th>Nome</th>
												<th>Nascido em</th>
												<th>Sexo</th>
												<th>E-mail</th>
												<th>Status</th>
												<th>Ação</th>
											</tr>
										</thead>
										<tbody>
											<?php foreach ($this->rsPacientes as $rPaciente) : ?>
												<tr>
                                                	<td>
                                                		<?php $imagem = empty($rPaciente['id_foto']) ?'/assets/img/user.png' : '/img/fotos/'.$rPaciente['id_entidade'].'.png';?>
                                                    	<img width="45" height="50" class="chat-avatar" src="<?php  echo $this->baseUrl($imagem)?>"><br/>
														<?php echo str_pad($rPaciente['id_entidade'], 5, "0", STR_PAD_LEFT); ?>
													</td>
                                                    <td>
                                                        <?php echo $rPaciente['st_nome'] ?>
                                                    </td>
                                                    <td>
                                                        <?php
                                                        	if(!empty($rPaciente["dt_nascimento"])){
	                                                            list($YY,$mm,$dd) = explode('-',$rPaciente["dt_nascimento"]);
	                                                            echo $dd.'/'.$mm.'/'.$YY; 
                                                        	}
                                                        ?>
                                                    </td>
                                                    <td><?php echo $rPaciente['st_sexo'] == 'M' ? 'Masculino' : 'Feminino' ?></td>
                                                    <td><?php echo $rPaciente['st_email'] ?></td>
                                                    <td><?php echo $rPaciente['id_ativo'] == 1 ? 'ATIVO':'INATIVO';?></td>
                                                    <td style="text-align: center;">
                										<a href="<?php echo $this->baseUrl('/corporativo/cliente/index/id/'.base64_encode($rPaciente["dt_nascimento"].'@'.$rPaciente['id_entidade']))?>"><span class="fa-edit s20" title="Editar Registro"></span></a> | 
                										<a href="<?php echo $this->baseUrl('/corporativo/cliente/inativarregistro/id/'.base64_encode($rPaciente["dt_nascimento"].'@'.$rPaciente['id_entidade']))?>"><span class="fa-remove s20" title="Inativar Registro"></span></a>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
										</tbody>
									</table>
								</div>
							</div>
						</div>
    				</div>
    			</form>
    		</div>
		<?php else :?>
            <div class="alert alert-danger fade in" style="text-align: center;">
                <strong>NÃO EXISTEM PACIENTES CADASTRADOS NA CLÍNICA, CLIQUE NO BOTÃO "ADICIONAR PACIENTE" PARA REALIZAR OS CADASTROS</strong>
            </div>
		<?php endif;?>
	</div>
	<div class="clearfix"></div>
</div>

<script src="<?php echo $this->baseUrl()?>/assets/plugins/tables/datatables/jquery.dataTables.js"></script>
<script src="<?php echo $this->baseUrl()?>/assets/plugins/tables/datatables/dataTables.tableTools.js"></script>
<script src="<?php echo $this->baseUrl()?>/assets/plugins/tables/datatables/dataTables.bootstrap.js"></script>
<script src="<?php echo $this->baseUrl()?>/assets/plugins/tables/datatables/dataTables.responsive.js"></script>
<script src="<?php echo $this->baseUrl()?>/assets/js/pages/data-tables.js"></script>