<?php $dados = $this->dadospagina;?>

<div id="content">
	<div class="content-wrapper">
		<div class="row">
			<div class="col-lg-12 heading">
                <h1 class="page-header"><i class="ec-pencil2"></i><strong>CADASTRO DE USUÁRIOS</strong></h1>
                <div style="text-align: right;">
					<a href="<?php echo $this->baseUrl('/usuario/usuario/listagem')?>">
						<button class="btn btn-dark" type="button">ACESSAR LISTAGEM DE USUÁRIOS</button>
					</a>
				</div>
            </div>
		</div>
		
		<div class="tabs">
			<ul class="nav nav-tabs">
				<li class="active"><a data-toggle="tab" href="#home2">DADOS PESSOAIS</a></li>
				<li class=""><a data-toggle="tab" href="#profile2">ACESSOS</a></li>
			</ul>
			
			<div class="tab-content">
				<div id="home2" class="tab-pane fade active in">
					<div class="outlet">
						<form id="formCadastro" class="form-horizontal group-border hover-stripped" role="form" method="post" action="<?php echo $this->baseUrl('/usuario/usuario/index')?>">
							<input type="hidden" id="imagem" name="imagem" value="">
							<input type="hidden" id="id_foto" name="id_foto" value="<?php echo $dados['geral']['sn_foto']?>">
							<input type="hidden" id="usuario" name="usuario" value="<?php echo $dados['geral']['id_usuario']?>">
							<div class="row">
								<div class="col-lg-9 col-md-9 col-sm-9 col-xs-12" id="wrapper_booth" style="display: none;">
									<div class="panel panel-primary">
										<div class="panel-heading">
											<h4 class="panel-title" style="text-align: center;">									
												<span>Compartilhe o dispositivo, clique no crop (Quadrado pontilhado)::: para limitar o tamanho da foto, enquadre com o rosto do cliente e clique na câmera para tirar a foto</span>
											</h4>
										</div>
										<div class="panel-body">
											<div id="wrapper">
                            					<div id="example"></div>       
                                    		</div>
										</div>
									</div>
								</div>
								
								<div class="col-lg-3 col-md-3 col-sm-3">
									<div class="panel panel-default plain">
										<div class="panel-heading white-bg"></div>
										<div class="panel-body">
											<div class="form-group">
												<div class="col-lg-12 col-md-12" align="center">
												    <?php $imagem = empty($dados['geral']['sn_foto']) ?'/assets/img/user.png' : '/img/fotos/usuario/'.$dados['geral']['id_usuario'].'.png';?>
													<img id="foto" name="foto" alt="" style="cursor: pointer;" src="<?php echo $this->baseUrl($imagem)?>">
												</div>
											</div>
										</div>
									</div>
								</div>
							
								<div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
									<div class="panel panel-default plain">
										<div class="panel-heading white-bg"></div>
										<div class="panel-body">
											<div class="form-group">
												<label class="col-lg-2 col-md-2 col-sm-12 control-label">LOGIN<b style="color: red;"> *</b></label>
												<div class="col-lg-6 col-md-6">
													<input class="form-control" type="text" id="st_usuario" name="st_usuario" placeholder="nome.sobrenme" maxlength="40" required value="<?php echo $dados['geral']['st_usuario']?>" />
												</div>												
												<div class="col-lg-3 col-md-3">
													<label class="checkbox-inline">
														<input type="checkbox" value="1" <?php if($dados['geral']['id_ativo']==1){ echo 'checked ="checked"';}?> style="position: absolute; opacity: 0;" id="id_ativo" name="id_ativo"  />ATIVO
													</label>
												</div>
											</div>
											<div class="form-group">
												<label class="col-lg-2 col-md-2 col-sm-12 control-label ">NOME<b style="color: red;"> *</b></label>
												<div class="col-lg-9 col-md-9">
													<input type="text" class="form-control" autofocus="autofocus" id="nm_usuario" name="nm_usuario" required  value="<?php echo $dados['geral']['nm_usuario']?>" />
												</div>
											</div>
											<div class="form-group">
												<label class="col-lg-2 col-md-2 col-sm-12 control-label">NASCIDO EM<b style="color: red;"> *</b></label>
												<div class="col-lg-3 col-md-3">
													<input type="text" class="form-control" id="dt_nascimento" name="dt_nascimento" required  value="<?php echo $dados['geral']['dt_nascimento']?>" />
												</div>
												
												<label class="col-lg-2 col-md-2 col-sm-12 control-label">SEXO<b style="color: red;"> *</b></label> 
												<div class="col-lg-5 col-md-5">
													<label class="radio-inline"> <input type="radio" name="st_sexo" value="M" <?php if($dados['geral']['ds_sexo'] == "M")  echo "checked"?> required >Masculino</label> 
													<label class="radio-inline"> <input type="radio" name="st_sexo" value="F" <?php if($dados['geral']['ds_sexo'] == "F")  echo "checked"?> required >Feminino</label>
												</div>
											</div>
											<div class="form-group">
												<label class="col-lg-2 col-md-2 col-sm-12 control-label">TELEFONE<b style="color: red;"> *</b></label>
												<div class="col-lg-4 col-md-4">
													<input type="text" class="form-control" id="st_fonecontato" name="st_fonecontato" required value="<?php echo $dados['geral']['nr_telefone']?>" />
												</div>
												<label class="col-lg-2 col-md-2 col-sm-12 control-label">CELULAR</label>
												<div class="col-lg-4 col-md-4">
													<input type="text" class="form-control" id="st_fonecelular" name="st_fonecelular" required value="<?php echo $dados['geral']['nr_celular']?>" />
												</div>
											</div>
										</div>
									</div>
								</div>
											
								<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
									<div class="panel panel-default plain">
										<div class="panel-heading white-bg"></div>
										<div class="panel-body">
										  <div class="form-group">
												<label class="col-lg-1 col-md-1 col-sm-12 control-label">CPF<b style="color: red;"> *</b></label>
												<div class="col-lg-3 col-md-3">
													<input type="text" class="form-control" id="st_cpf" name="st_cpf" required value="<?php echo $dados['geral']['nr_cpf']?>" />
												</div>
												<label class="col-lg-1 col-md-1 col-sm-12 control-label">RG</label>
												<div class="col-lg-2 col-md-2">
													<input type="text" class="form-control" id="st_rg" name="st_rg" maxlength="10" value="<?php echo $dados['geral']['nr_rg']?>" />
												</div>
												<label class="col-lg-1 col-md-1 col-sm-12 control-label">EMAIL<b style="color: red;"> *</b></label>
												<div class="col-lg-4 col-md-4">
													<input type="text" class="form-control" id="st_email" name="st_email" required value="<?php echo $dados['geral']['ds_email']?>" />
												</div>
											</div>																			
											<div class="form-group">
												<label class="col-lg-1 col-md-1 col-sm-12 control-label">SENHA </label>
												<div class="col-lg-5 col-md-5">
													<input id="password" class="form-control" type="password" name="password">
												</div>												
												<label class="col-lg-2 col-md-2 col-sm-12 control-label">CONFIRMA SENHA</label>
												<div class="col-lg-4 col-md-4">
													<input id="confirm_password" class="form-control" type="password" name="confirm_passowrd">
												</div>
											</div>										
										</div>
									</div>
								</div>					
								<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
									<div class="panel panel-default toggle">
										<ul class="breadcrumb" style="text-align: center;">
											<li>
												<button class="btn btn-success  ml15" type="submit">Salvar</button>
												<button class="btn btn-primary" type="reset" id="btnLimpar">Limpar</button>
											</li>
										</ul>
									</div>	
								</div>
							</div>
						</form>
					</div>
				</div>
								
				<div id="profile2" class="tab-pane fade">
					<div class="outlet">
						<form class="form-horizontal group-border hover-stripped" method="post" id="formPerfil" name="formPerfil">
							<input type="hidden" id="id_usuario" name="id_usuario" value="<?php echo $dados['geral']['id_usuario']?>" />					
							<div class="row">
								<div class="col-lg-12">
									<div class="panel panel-default plain">
										<div class="panel-heading white-bg"></div>
										<div class="panel-body">
											<div class="form-group">
												<label class="col-lg-2 col-md-2 col-sm-12 control-label">MULT-EMPRESA<b style="color: red;"> *</b></label>
												<div class="col-lg-4 col-md-4">
													<select id="id_organizacao" class="form-control select2" required name="id_organizacao">
														<option></option>
														<?php foreach ($this->organizacao as $value):?>
															<option value="<?php echo $value['id_organizacao']?>"><?php echo strtoupper( $value['st_nome_fantasia']) ?></option>
														<?php endforeach;?>
													</select>
												</div>
											</div>
											<div class="form-group">
												<label class="col-lg-2 col-md-2 col-sm-12 control-label">PERFIL<b style="color: red;"> *</b></label>
												<div class="col-lg-4 col-md-4">
													<select id="id_perfil" class="form-control select2" required name="id_perfil">
														<option></option>
														<?php foreach ($this->perfil as $value):?>
															<option value="<?php echo $value['id_perfil']?>"><?php echo strtoupper( $value['st_nome']) ?></option>
														<?php endforeach;?>
													</select>
												</div>
											</div>																						
										</div>
									</div>
								</div>
								<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
									<div class="panel panel-default toggle">
										<ul class="breadcrumb" style="text-align: center;">
											<li>
												<button class="btn btn-success  ml15" id="btnAddPerfil" type="button">Adicionar</button>
											</li>
										</ul>
									</div>	
								</div>
							</div>
						</form>
					</div>
					<div class="outlet">
						<div class="slimScrollDiv" style="position: relative; overflow: hidden; width: 100%; height: auto;">
							<div class="table-responsive" style="overflow: hidden; width: 100%; height: auto;">
								<table class="table table-bordered">
									<thead>
										<tr>
											<th style="text-align: center;">Mult-Empresa</th>
											<th style="text-align: center;">Perfil</th>
											<th style="text-align: center;">Status</th>
											<th style="text-align: center;">Ação</th>
										</tr>
									</thead>
									<tbody>
										<?php foreach ($dados['perfil'] as $rsPerfil) : ?>
											<tr>
												<td><?php echo strtoupper($rsPerfil['st_nome_fantasia']); ?></td>
												<td><?php echo strtoupper($rsPerfil['st_nome']) ?></td>
                                                <td><?php echo $rsPerfil['sn_ativo'] == 1 ? 'ATIVO':'INATIVO';?></td>
                                                <td style="text-align: center;">
                									<a><span class="fa-remove s20" title="Inativar Registro" onclick="excluirRegistro(<?php echo $rsPerfil['cd_organizacao'] ?>,<?php echo $rsPerfil['cd_usuario'] ?>)" style="cursor: pointer;"></span></a>
                                                </td>
                                            </tr>
										<?php endforeach; ?>
									</tbody>
								</table>
							</div>
							<div class="slimScrollBar ui-draggable" style="background: rgb(153, 153, 153) none repeat scroll 0% 0%; height: 5px; position: absolute; bottom: 3px; opacity: 0.4; display: none; border-radius: 5px; z-index: 99; width: 1060px; left: 0px;"></div>
							<div class="slimScrollRail" style="width: 100%; height: 5px; position: absolute; bottom: 3px; display: none; border-radius: 5px; background: rgb(51, 51, 51) none repeat scroll 0% 0%; opacity: 0.5; z-index: 90;"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="clearfix"></div>
</div>

<!-- ModalCPFIguais -->
<div class="modal fade" id="modalCPF">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Existe(m) esse(s) Registro(s) para esse CPF</h4>
            </div>
              <div class="modal-body">
                <div class="row">
					<div id="RegCpf"></div>       
        		</div>            
            </div>
            <div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">Continuar Cadastro</button>
          </div>
        </div>
    </div>
</div>
<!-- Fim Modal CPF iguais--> 

<!-- Modal valida CPF -->
<div class="modal" id="modalVal">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">Alerta</h4>
            </div>
              <div class="modal-body">
                <div class="row">
					<div>O CPF digitado não é valido</div>       
        		</div>            
            </div>
            <div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
          </div>
        </div>
    </div>
</div>
<!-- Fim Modal valida CPF--> 


<?php if(!empty($this->msg)):?>
	<?php if($this->msg == 2) :?>
		<div class="alert alert-success fade in">
			<button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
			<i class="fa-ok alert-icon s24"></i>
			<strong>Registro gravado com sucesso!</strong>
		</div>
	<?php else :?>
		<div class="alert alert-danger fade in">
			<button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
			<strong>Ocorreu um erro ao gravar!</strong>
		</div>
	<?php endif;?>
<?php endif;?>

<script type="text/javascript" src="<?php echo $this->baseUrl('/js/photobooth/photobooth_min.js')?>"> </script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/photobooth/script.js')?>"> </script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/photobooth/hijs.js')?>"> </script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/usuario/usuario.js')?>"> </script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/plugins/function.js')?>"> </script>
<link href="<?php echo $this->baseUrl('/js/photobooth/page.css')?>" rel="stylesheet" />

<script src="<?php echo $this->baseUrl()?>/assets/plugins/forms/maxlength/bootstrap-maxlength.js"></script>
<script src="<?php echo $this->baseUrl()?>/assets/plugins/forms/bootstrap-filestyle/bootstrap-filestyle.js"></script>
<script src="<?php echo $this->baseUrl()?>/assets/plugins/forms/maskedinput/jquery.maskedinput.js"></script>