<!-- Modal -->
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Atendimento Médico</h4>
            </div>
          
              <div class="modal-body">
                <div class="row">
                    <div class="col-lg-09">
                        <!-- Start col-lg-12 -->
                        <div class="panel panel-default toggle" id="spr_0">
                            <!-- Start .panel -->
                            <div class="panel-heading">
                                <h3 class="panel-title"><span id='viewData' style="font-weight: bold"></span></h3>
                                <div class="panel-controls panel-controls-hide" style="display: none;">
                                    <a class="toggle panel-minimize" href="#"><i class="im-minus"></i></a>
                                </div>
                            </div>
                            
                            <div class="panel-body">
                            
                                <form role="form" class="form-horizontal group-border hover-stripped">         
                                    <div class="form-group">                                
                                        <label class="col-lg-2 col-md-2 col-sm-12 control-label">                                     
                                            <div class="col-lg-5 col-md-5">
                                                <div class="form-group">
                                					<div class="col-lg-9 col-md-9">
                                						<img src="<?php echo $this->baseUrl()?>/assets/img/user.png" alt="" width='105px'>
                                					</div>
                                				</div>                                    
                        				    </div>
                    				    </label>
                                            
                                        <div class="col-lg-9 col-md-9">
                                            <div class="row">                                            
                                                <div class="col-lg-6 col-md-6">
                                                    <input type="text" class="form-control left-icon" style="border:1px solid red;">
                                                    <i class="ec-user s16 left-input-icon"></i>
                                                    <span class="help-block">Nome cliente</span>
                                                </div>                                            
                                                <div class="col-lg-3 col-md-3">
                                                    <input type="text" class="form-control">
                                                    <span class="help-block">CPF</span>
                                                </div>
                                                <div class="col-lg-3 col-md-3">
                                                    <input type="text" class="form-control">
                                                    <span class="help-block">Data nascimento</span>
                                                </div>
                                                <div class="col-lg-6 col-md-6">
                                                    <input type="text" class="form-control left-icon"><i class="ec-mail s16 left-input-icon"></i>
                                                    <span class="help-block">Endereço de e-mail</span>
                                                </div>
                                                                                   
                                                <div class="col-lg-3 col-md-3">
                                                    <input type="text" class="form-control left-icon"><i class="fa-phone s16 left-input-icon"></i>
                                                    <span class="help-block">Telefone Fixo</span>
                                                </div>
                                                <div class="col-lg-3 col-md-3">
                                                    <input type="text" class="form-control left-icon"><i class="st-phone s16 left-input-icon"></i>
                                                    <span class="help-block">Telefone Celular</span>
                                                </div>  
                                            </div>
                                        </div>
                                    </div>
                                    
                                   <div class="form-group">
                                        <label class="col-lg-2 col-md-2 col-sm-12 control-label">Consulta</label>
                                        <div class="col-lg-10 col-md-10">
                                            <div class="row">                                           
                                               <div class="col-lg-6 col-md-6">
                                                    <div class="select2-container form-control select2" id="s2id_autogen1"><a tabindex="-1" class="select2-choice"  href="javascript:void(0)">   
                                                        <span class="select2-chosen">Dr. Júlio Andrade Neto</span>
                                                        <abbr class="select2-search-choice-close"></abbr>   
                                                        <span class="select2-arrow"><b></b></span></a>
                                                        <input type="text" class="select2-focusser select2-offscreen" id="s2id_autogen2">
                                                    </div>                                              
                                                    <span class="help-block">Médico atendente</span>
                                                </div>
                                                <div class="col-lg-3 col-md-6">
                                                    <span class="ui-spinner ui-widget ui-widget-content ui-corner-all"><input type="text" value="08:30 PM" name="spinner-time" id="spinner-time" class="form-control ui-spinner-input" aria-valuenow="1420151640000" autocomplete="off" role="spinbutton"><a class="ui-spinner-button ui-spinner-up ui-corner-tr" tabindex="-1"><span class="ui-icon ui-icon-triangle-1-n">▲</span></a><a class="ui-spinner-button ui-spinner-down ui-corner-br" tabindex="-1"><span class="ui-icon ui-icon-triangle-1-s">▼</span></a></span>
                                                    <span class="help-block">Data Consulta</span> 
                                                </div>
                                                <div class="col-lg-3 col-md-6">
                                                    <span class="ui-spinner ui-widget ui-widget-content ui-corner-all"><input type="text" value="08:30 PM" name="spinner-time" id="spinner-time" class="form-control ui-spinner-input" aria-valuenow="1420151640000" autocomplete="off" role="spinbutton"><a class="ui-spinner-button ui-spinner-up ui-corner-tr" tabindex="-1"><span class="ui-icon ui-icon-triangle-1-n">▲</span></a><a class="ui-spinner-button ui-spinner-down ui-corner-br" tabindex="-1"><span class="ui-icon ui-icon-triangle-1-s">▼</span></a></span>
                                                    <span class="help-block">Hora Consulta</span> 
                                                </div>   
                                            </div>
                                        </div>
                                    </div>                                 
                                    
                                    <div class="form-group">
                                        <label class="col-lg-2 col-md-2 col-sm-12 control-label">Cobertura</label>
                                        <div class="col-lg-5 col-md-5">
                                            <div class="select2-container form-control select2" id="s2id_autogen1"><a tabindex="-1" class="select2-choice"  href="javascript:void(0)">   
                                                <span class="select2-chosen">Convênio</span>
                                                <abbr class="select2-search-choice-close"></abbr>   
                                                <span class="select2-arrow"><b></b></span></a>
                                                <input type="text" class="select2-focusser select2-offscreen" id="s2id_autogen2">
                                            </div> 
                                            <p></p>
                                            <input type="email" placeholder="Procedimento" class="form-control">
                                        </div>
                                        <div class="col-lg-5 col-md-5">
                                            <div class="select2-container form-control select2" id="s2id_autogen1"><a tabindex="-1" class="select2-choice"  href="javascript:void(0)">   
                                                <span class="select2-chosen">Plano</span>
                                                <abbr class="select2-search-choice-close"></abbr>   
                                                <span class="select2-arrow"><b></b></span></a>
                                                <input type="text" class="select2-focusser select2-offscreen" id="s2id_autogen2">
                                            </div> 
                                            <p></p>
                                            <button class="btn btn-danger" type="button">Verifica Elegibilidade</button>
                                        </div>                                     
                                    </div>                        
                                    <div class="form-group">
                                        <label class="col-lg-2 col-md-2 col-sm-12 control-label">Observações</label>
                                        <div class="col-lg-10 col-md-10">
                                            <textarea rows="3" class="form-control"></textarea>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <!-- End .panel -->
                    </div>
        		</div>            
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">Cadastrar</button>
          </div>
        </div>
    </div>
</div>
<!-- Fim Modal --> 

<!-- Start #content -->
<div id="content">
    <!-- Start .content-wrapper -->
    <div class="content-wrapper">
        <div class="row">
            <!-- Start .row -->
            <!-- Start .page-header -->
            <div class="col-lg-12 heading">
                <h1 class="page-header"><i class="ec-archive"></i> Atendimento Médico</h1>
                <!-- Start .bredcrumb -->
                <ul id="crumb" class="breadcrumb">
                </ul>
                <!-- End .breadcrumb -->
                <!-- Start .option-buttons -->
                <div class="option-buttons">
                    <div class="btn-toolbar" role="toolbar">
                        <div class="btn-group">
                            <a id="clear-localstorage" class="btn tip" title="Reset panels position">
                                <i class="ec-refresh color-red s24"></i>
                            </a>
                        </div>
                        <div class="btn-group dropdown">
                            <a class="btn dropdown-toggle" data-toggle="dropdown" id="dropdownMenu1"><i class="br-grid s24"></i></a>
                            <div class="dropdown-menu pull-right" role="menu" aria-labelledby="dropdownMenu1">
                                <div class="option-dropdown">
                                    <div class="shortcut-button">
                                        <a href="#">
                                            <i class="im-pie"></i>
                                            <span>Earning Stats</span>
                                        </a>
                                    </div>
                                    <div class="shortcut-button">
                                        <a href="#">
                                            <i class="ec-images color-dark"></i>
                                            <span>Gallery</span>
                                        </a>
                                    </div>
                                    <div class="shortcut-button">
                                        <a href="#">
                                            <i class="en-light-bulb color-orange"></i>
                                            <span>Fresh ideas</span>
                                        </a>
                                    </div>
                                    <div class="shortcut-button">
                                        <a href="#">
                                            <i class="ec-link color-blue"></i>
                                            <span>Links</span>
                                        </a>
                                    </div>
                                    <div class="shortcut-button">
                                        <a href="#">
                                            <i class="ec-support color-red"></i>
                                            <span>Support</span>
                                        </a>
                                    </div>
                                    <div class="shortcut-button">
                                        <a href="#">
                                            <i class="st-lock color-teal"></i>
                                            <span>Lock area</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="btn-group dropdown">
                            <a class="btn dropdown-toggle" data-toggle="dropdown" id="dropdownMenu2"><i class="ec-pencil s24"></i></a> 
                            <div class="dropdown-menu pull-right" role="menu" aria-labelledby="dropdownMenu2">
                                <div class="option-dropdown">
                                    <div class="row">
                                        <p class="col-lg-12">Quick post</p>
                                        <form class="form-horizontal" role="form">
                                            <div class="form-group">
                                                <div class="col-lg-12">
                                                    <input type="text" class="form-control" placeholder="Enter title">
                                                </div>
                                            </div>
                                            <!-- End .form-group  -->
                                            <div class="form-group">
                                                <div class="col-lg-12">
                                                    <textarea class="form-control wysiwyg" placeholder="Enter text"></textarea>
                                                </div>
                                            </div>
                                            <!-- End .form-group  -->
                                            <div class="form-group">
                                                <div class="col-lg-12">
                                                    <input type="text" class="form-control tags1" placeholder="Enter tags">
                                                </div>
                                            </div>
                                            <!-- End .form-group  -->
                                            <div class="form-group">
                                                <div class="col-lg-12">
                                                    <button class="btn btn-default btn-xs">Save Draft</button>
                                                    <button class="btn btn-success btn-xs pull-right">Publish</button>
                                                </div>
                                            </div>
                                            <!-- End .form-group  -->
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="btn-group">
                            <a class="btn dropdown-toggle" data-toggle="dropdown" id="dropdownMenu3"><i class="ec-help s24"></i></a>
                            <div class="dropdown-menu pull-right" role="menu" aria-labelledby="dropdownMenu3">
                                <div class="option-dropdown">
                                    <p>First time visitor ? <a href="#" id="app-tour" class="btn btn-success ml15">Take app tour</a> 
                                    </p>
                                    <hr>
                                    <p>Or check the <a href="#" class="btn btn-danger ml15">FAQ</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End .option-buttons -->
            </div>
            <!-- End .page-header -->
        </div>
        <!-- End .row -->
        <div class="outlet">
            <!-- Start .outlet -->
            <!-- Page start here -->
            <div id="email-sidebar">
                <!-- Start #email-sidebar -->
                <div class="p15">
                    <a id="write-email" href="#" class="btn btn-danger btn-block uppercase"><i class="im-alarm"></i> Consultas do dia</a>
                </div>
                <ul id="email-nav" class="nav nav-pills nav-stacked">
                    <div id="calendario" style="padding: 0px 7px 7px 7px"></div>
                    <li class="nav-header">Status Consulta</li>
                    <li><a href="#"><span class="circle"></span> Agendadas</a>
                    </li>
                    <li><a href="#"><span class="circle color-red"></span> Cancelada</a>
                    </li>
                    <li><a href="#"><span class="circle color-green"></span> Confirmadas</a>
                    </li>
                    <li><a href="#"><span class="circle color-teal"></span> Atendida</a>
                    </li>
                </ul>
            </div>
            <!--End #email-sidebar -->
            <div id="email-content">
                <!-- Start #email-content -->
                <div class="email-wrapper">
                    <div class="email-toolbar col-lg-12">
                        <div class="pull-left" role="toolbar">
                            <button id="email-toggle" class="email-toggle" type="button">
                                <span class="sr-only">Toggle email nav</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a href="#" class="btn btn-default btn-round btn-sm tip mr5" title="Refresh inbox"><i class="ec-refresh s16"></i></a>
                            <a href="#" class="btn btn-default btn-round btn-sm tip mr5" title="Print"><i class="fa-print s16"></i></a>
                        </div>
                        <ul class="email-pager">
                            <li class="pager-info"></li>
                            <li><a href="#" class="btn btn-default btn-round btn-sm"><i class="en-arrow-left4 s16"></i></a></li>
                            <li><a href="#" class="btn btn-default btn-round btn-sm"><i class="en-arrow-right5 s16"></i></a></li>
                        </ul>
                    </div>
                    
                    <div class="email-list col-lg-12">
                        
                        <?php if ($this->dadosConsulta):?>
                            <?php foreach ($this->dadosConsulta as $id => $data):?>
                            
                                <div class="panel panel-primary" id="spr_0">
                                    <?php foreach ($data['medicos'] as $id2 => $medicos):?>                                        
                                                
                                        <div class="panel-heading">
                                            <h4 class="panel-title"><i class="fa-user-md"></i> Agenda de <span style="font-size:20px; font-weight: bold"><?php echo $medicos['nome'] ?></span>, <span style="font-size:20px;"><?php echo date('d') .' de '. date('F') .' de ' . date('Y')?>.</span></h4>
                                        </div>
                                           
                                        <div class="panel-body">                                
                                            <table class="table table-striped table-hover table-fixed-layout non-responsive">
                                                <tbody>
                                                    
                                                        <?php foreach ($medicos['atendimentos'] as $k => $dado){
                                                                $procedimento = null; $obs = null; $paciente = null;
                                                                $paciente = $dado['cliente']['nome'];
                                                                $class = 'label label-success mr10';
                                                                $confirm = 'im-star3 s20';
                                                            ?>
                                                            <tr>
                                                                <td class="email-select input-mini">
                                                                    <label class="checkbox"><span class="<?php echo $class?>"><i class="br-clock"></i> <?php echo $dado['hora'];?></span></label>
                                                                </td>
                                                                <td class="email-star input-mini"><a title="" class="btn btn-danger btn-round btn-sm tip mr5" href="#" onclick="agendarConsulta('<?php echo $medicos['nome']?>');" data-original-title="Atender Paciente"><i class="en-checkmark s16"></i></a>
                                                                </td>
                                                                <td class="email-subject"> 
                                                                    <?php if($paciente == null):?>
                                                                        <button class="btn btn-sm btn-primary btn-alt" type="button" onclick="agendarConsulta('<?php echo $medicos['nome']?>');"><i class="br-plus"></i> Agendar</button>
                                                                    <?php else : ?>
                                                                        <span data-toggle="popover" title="<?php echo $paciente?>" data-content="Telefone Fixo: (61) 3299-1187 Telefone Celular: (61) 9844-1187 Convênio: Particular"  class="avatar"><img alt="@chadengle" title="Contato: (61) 8441-1902" src="<?php echo $this->baseUrl()?>/assets/img/avatars/<?php echo $dado['cliente']['id']?>.jpg" class="chat-avatar"></span>
                                                                        <?php echo $paciente?>
                                                                    <?php endif;?>
                                                                </td>
                                                                <td class="email-intro">
                                                                    <a href="#">
                                                                        <span class="label label-pink mr10"><?php echo $dado['procedimento']['nome']?></span> <?php echo $dado['status']['nome']?>
                                                                    </a>
                                                                </td>
                                                            </tr> 
                                                      <?php }?>                         
                                                </tbody>
                                                
                                            </table>
                                            
                                        </div><hr>
                                    <?php endforeach;?>
                                </div>
                            <?php endforeach; ?>
                            
                        <?php endif;?>
                       
                    </div>
                </div>
            </div>
        </div>
        <!-- End .outlet -->
    </div>
    <!-- End .content-wrapper -->
    <div class="clearfix"></div>
</div>
<!-- End #content -->
<!-- Javascripts --> 
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/atendimento/agendamentocadastro.js')?>"> </script>