<td width="98%" valign="top" align="center">
  <table cellspacing="0" cellpadding="0" border="0" style="font-family:Arial;background-color: #D3D3D3">
    <tbody>
    <tr>
      <td height="20px" colspan="3">&nbsp;</td>
    </tr>
    <tr>
      <td width="20" style="min-width: 20px">&nbsp;&nbsp;&nbsp;</td>
      <td width="515" align="center">
        <table bgcolor="#FFFFFF" width="100%" cellspacing="0" cellpadding="0" border="0" style="font-family:Arial;border:solid 1px #dddddd;border-radius:8px">
          <tbody>
          <tr>
            <td colspan="3">
              <table width="1" cellspacing="0" cellpadding="0" border="0">
                <tbody>
                <tr>
                  <td>
                    <div style="min-height:20px;font-size:15px;line-height:15px">&nbsp;</div>
                  </td>
                </tr>
                </tbody>
              </table>
            </td>
          </tr>
          <tr>
            <td>
              <table width="30" cellspacing="0" cellpadding="0" border="0">
                <tbody>
                <tr>
                  <td>
                    <div style="min-height:0px;font-size:0px;line-height:0px">&nbsp;</div>
                  </td>
                </tr>
                </tbody>
              </table>
            </td>
            <td valign="top" align="">
            
              <table width="100%" cellspacing="0" cellpadding="0" border="0" style="color: #454141">
                <tbody>
                <tr>
                  <td align="left" style="font-family:arial,sans-serif;font-size: 28px; color: #555; font-weight: bold;">
                    <img src="http://clinicafluxus.tecnolabs.com.br/images/logo-min2.png" width="100px"> <?php echo $this->config->cliente->database->nmEmpresa?>
                  </td>
                </tr>
                <tr>
                  	<td align="left" style="color: #555; font-family:arial,sans-serif;font-size:18px; border-bottom: 1px solid darkgray; padding-bottom: 5px;">
                  		Contato pelo Site - <?php echo $this->config->cliente->database->site?>
					</tr>
                <tr>
                  <td>
                    <table width="1" cellspacing="0" cellpadding="0" border="0">
                      <tbody>
                      <tr>
                        <td>
                          <div style="min-height:10px;font-size:10px;line-height:20px">&nbsp;</div>
                        </td>
                      </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
                
			    <tr>
			      <td align="left" style="font-family:arial,sans-serif;font-size:14px">
			        Olá <?php echo $this->config->cliente->database->nmEmpresa?>! <br><br>Uma nova solicitação de <?php echo strToUpper($this->tipo)?> de <strong><?php echo $this->nome ?></strong> (<?php echo $this->email?>) acaba de ser cadastrado,
			        segue abaixo os detalhes deste evento:
			      </td>
			    </tr>
    <tr>
      <td align="left" style="font-family:arial,sans-serif;font-size:14px; padding-top: 10px; padding-bottom: 15px;">
        
      </td>
    </tr>
    <tr>
      <td align="left" style="font-family:arial,sans-serif;font-size:14px">
        <table style="color: #454141"><tbody>
<tr>
  <td width="20"></td>
  <td style="font-size:16px">
  	
    	<span style="color:red"><?php echo $this->conteudo?></span>
    
        <br>
        <span style="font-size: 12px">
              <!--  <a href="#" style="color: " class="manage-link">ver detalhes do compromisso</a> -->
        </span>
  </td>
  <td width="20"></td>
</tr>
</tbody></table>

	<!-- <br>Desenvolvido por <a href="http://www.tecnolabs.com.br">www.tecnolabs.com.br</a><br>  -->

      </td>
    </tr>

                <tr>
                  <td style="font-family:arial,sans-serif;font-size:14px; padding-bottom: 45px;">
                  </td>
                </tr>
                <tr>
                  <td width="100%" style="padding-top: 5px; padding-bottom: 3px;">
                    <table width="515">
                      <tbody>
                      <tr>
                        <td align="left" style="color:#777;font-family:Arial,sans-serif;font-size:11px; padding-top: 0px;">
                            Não quer receber mail e-mails? <a class="unsubscribe-link" href="#">Cancelar assinatura</a>.<br>
                        </td>
                        <td align="right" style="padding-top: 0px; color:#a9a9a9; font-size: 12px;">
                          <table width="220">
                            <tbody><tr>
                              <td width="60%" valign="middle" align="right" style="padding-right: 2px; color:#a9a9a9; font-size: 12px;">
                                via TecnoLabs
                              </td>
                              <td valign="bottom">
                                   <span><a href="http://www.tecnolabs.com.br"> <img border="0" src="http://www.tecnolabs.com.br/images/logo.png" width="150px" alt="TecnoLabs"></a></span> 
                              </td>
                            </tr>
                          </tbody></table>
                        </td>
                      </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
                </tbody>
              </table>
            </td>
            <td>
              <table width="30" cellspacing="0" cellpadding="0" border="0">
                <tbody>
                <tr>
                  <td>
                    <div style="min-height:0px;font-size:0px;line-height:0px">&nbsp;</div>
                  </td>
                </tr>
                </tbody>
              </table>
            </td>
          </tr>
          </tbody>
        </table>
      </td>
      <td width="20" style="min-width: 20px">&nbsp;&nbsp;&nbsp;</td>
    </tr>
    <tr>
      <td height="20px" colspan="3">
              &nbsp;
      </td>
    </tr>
    </tbody>
  </table>
</td>
